#!/usr/bin/env python
# vim:et:sta:sts=4:sw=4:ts=8:tw=79:
# -*- coding: utf-8 -*-

from __future__ import print_function
import sys
import os.path
import json

def splitdeps(deps):
    splitdeps = deps.split(',')
    for index, item in enumerate(splitdeps):
        splitdeps[index] = item.strip()
        if '|' in item:
            splitdeps[index] = item.split('|')
    splitdeps[:] = [i for i in splitdeps if i != '']
    return splitdeps

if len(sys.argv) != 2:
    print("ERROR: you have to provide the path to a PACKAGES.TXT file")
    sys.exit(1)

pkgtxt = sys.argv[1]

if not os.path.isfile(pkgtxt):
    print("ERROR: file {} not found.".format(pkgtxt))
    sys.exit(1)

# location descriptions
locdesc = {
    "a" : "The base system. Contains software to get up and running and have a text editor and basic communications programs",
    "ap" : "Various applications that do not require the X Window System",
    "d" : "Program development tools. Compilers, debuggers, interpreters, and man pages. It's all here",
    "e" : "GNU Emacs",
    "f" : "FAQs, HOWTOs, and other miscellaneous documentation",
    "games" : "Games :)",
    "gnome" : "Applications and libraries from the Gnome project",
    "k" : "Linux kernel",
    "kde" : "KDE applications (depending on kdelibs)",
    "kdei" : "Localisation packages for KDE applications",
    "l" : "Libraries",
    "locale" : "Localisation Packages",
    "lxde" : "LXDE packages",
    "mate" : "MATE Desktop Environment Packages",
    "n" : "Networking programs. Daemons, mail programs, telnet, news readers, web servers and so on",
    "t" : "teTeX document formatting system",
    "tcl" : "Tcl/tk packages",
    "x" : "X Window System packages",
    "xap" : "Applications that require X to run",
    "xfce" : "Xfce packages",
    "y" : "BSD Games",
    "academic" : "Academic software",
    "accessibility" : "Accessibility packages",
    "audio" : "Audio playback and manipulation",
    "business" : "Business software",
    "desktop" : "Desktop applications",
    "development" : "Development tools",
    "gis" : "Geographic Information System software",
    "graphics" : "Graphics software and libraries",
    "ham" : "HAM radio software",
    "haskell" : "Haskell programming language and tools",
    "libraries" : "Libraries",
    "misc" : "Miscellaneous",
    "multimedia" : "Multimedia software",
    "network" : "Networking tools",
    "office" : "Office software and tools",
    "perl" : "Perl programming language tools and libraries",
    "python" : "Python programming language tools and libraries",
    "ruby" : "Ruby programming language tools and libraries",
    "system" : "System software and tools",
    "extra" : "Extra Slackware packages",
    "patches" : "Slackware packages patches"
}


locations = []
pkgdict = {}
pkgdict["packages"] = []

with open(pkgtxt, "r") as f:
    readDescription1stLine = False
    readingDescription = False
    pkgname = ''
    descriptionShort = ''
    descriptionLong = ''
    pkg = {}
    for line in f:
        if line.startswith('PACKAGE NAME:'):
            readDescription1stLine = False
            readingDescription = False
            descriptionShort = ''
            descriptionLong = ''
            pkg = {}
            pkgNameFull = line.replace('PACKAGE NAME:', '').strip()
            pkgNameFullSplit = pkgNameFull.rsplit('.', 1)[0].rsplit('-', 3)
            pkgname, pkgver, pkgarch, pkgrel = pkgNameFullSplit
            pkg["name"] = pkgname
            pkg["ver"] = pkgver
            pkg["arch"] = pkgarch
            pkg["rel"] = pkgrel
            pkg["descs"] = ""
            pkg["descl"] = ""
            pkg["loc"] = ""
            pkg["sizec"] = ""
            pkg["sizeu"] = ""
        elif line.startswith('PACKAGE LOCATION:'):
            location = line.replace('PACKAGE LOCATION:', '').strip()
            pkg["path"] = location + '/' + pkgNameFull
            pkg["source"] = "source/" + '/'.join(location.split('/')[1:]) + '/' + pkgname
            if location.startswith('./extra/'):
                location = 'extra'
            elif location.startswith('./patches/'):
                location = 'patches'
            else:
                location = location.rsplit('/')[-1]
            locations.append(location)
            pkg["loc"] = location
        elif line.startswith('PACKAGE SIZE (compressed):'):
            sizec = line.replace('PACKAGE SIZE (compressed):', '').strip()
            pkg["sizec"] = sizec
        elif line.startswith('PACKAGE SIZE (uncompressed):'):
            sizeu = line.replace('PACKAGE SIZE (uncompressed):', '').strip()
            pkg["sizeu"] = sizeu
        elif line.startswith('PACKAGE REQUIRED:'):
            deps = line.replace('PACKAGE REQUIRED:', '').strip()
            deps = splitdeps(deps)
            if len(deps) > 0:
                pkg["deps"] = deps
        elif line.startswith('PACKAGE CONFLICTS:'):
            deps = line.replace('PACKAGE CONFLICTS:', '').strip()
            deps = splitdeps(deps)
            if len(deps) > 0:
                pkg["con"] = deps
        elif line.startswith('PACKAGE SUGGESTS:'):
            deps = line.replace('PACKAGE SUGGESTS:', '').strip()
            deps = splitdeps(deps)
            if len(deps) > 0:
                pkg["sug"] = deps
        elif line.startswith('PACKAGE DESCRIPTION:'):
            readingDescription = True
        elif line.startswith('{}:'.format(pkgname)):
            descline = line.replace('{}:'.format(pkgname), '').strip()
            descline = descline.replace('"', "'")
            if readingDescription:
                if readDescription1stLine:
                    descriptionLong = descriptionLong + descline + ' '
                else:
                    descriptionShort = descline
                    pkg["descs"] = descriptionShort
                    readDescription1stLine = True
        elif line == '\n':
            if readingDescription:
                descriptionLong = descriptionLong.strip()
                pkg["descl"] = descriptionLong
                readingDescription = False
                readDescription1stLine = False
                pkgdict["packages"].append(pkg)



locations = set(locations)
used_locations = {}
for l in locations:
    used_locations[l] = locdesc[l]
pkgdict["locations"] = used_locations

print(json.dumps(pkgdict, ensure_ascii=False))
